version: "3.8"
services:
  main:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DJANGO_ENV=development
      - DJANGO_SETTINGS_MODULE=service.settings.development
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
