version: '3.8'

services:
  postgres:
    container_name: lsplanner-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: lsplanner
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  redis:
    container_name: lsplanner-redis
    image: redis:latest
    restart: always

  fastapi:
    container_name: lsplanner-fastapi-service
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://lsplanner:lsplanner@postgres:5432/lsplanner
      - REDIS_URL=redis://redis:6379/0
